owner: gbe0
repo: uptime

sites:
  ## Servers
  - name: GitLab
    url: $CHECK_GITLAB
  - name: cPanel Server 1
    url: $CHECK_CPANEL_01
  - name: cPanel Server 2
    url: $CHECK_CPANEL_02
  - name: Docker Server 1
    url: $CHECK_DOCKER_01
  ## VPN servers
  - name: VPN - Singapore, SG
    url: $CHECK_VPN_SIN
  - name: VPN - Fremont, USA
    url: $CHECK_VPN_FMT
  - name: VPN - Manila, PH
    url: $CHECK_VPN_MNL
  - name: VPN - Frankfurt, DE
    url: $CHECK_VPN_FRA
  - name: VPN - Sydney, AU
    url: $CHECK_VPN_SYD
  ## Services
  - name: Bookmarks
    url: $CHECK_SERVICE_BOOKMARKS
  - name: Accounting
    url: $CHECK_SERVICE_ACCOUNTING
  - name: Key Management Service IPv4
    check: "tcp-ping"
    url: $CHECK_SERVICE_KMS_IPV4
    port: $CHECK_SERVICE_KMS_PORT
  ## Websites
  - name: gbe0.com
    url: https://gbe0.com
  - name: wiki.gbe0.com
    url: https://wiki.gbe0.com

status-website:
  cname: uptime.gbe0.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "Uptime for my various servers and websites."
  introMessage: Uptime information for gbe0.com infrastructure.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

robotsText: "User-agent: * \n Disallow: /"
